namespace:
  name: prod
 
service:
  port: 7111
  
replicaCount: 5

containers:
  imagePullPolicy: Always

resources:
  requests:
    cpu: "350m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
